### ISSUE TITLE
Different Image-size in the CNN

### ISSUE THREAD

**Issue by Shahdoust** [marooncn/Defect-Detection-Classifier#2]
@marooncn Thanks for the Repo. 
I have different image size (960x960) and the defect parts are very tiny in the Image like 25x25. Do you have any suggestion to do the classification with CNN? Could you please help me here?
I really appreciate it.

**Comment by marooncn** [comment]
Hi @Shahdoust, you can consider split one image to many of small size just like us. Otherwise, you may try the deep learning approach, such as this paper: [Segmentation-Based Deep-Learning Approach for Surface-Defect Detection](https://arxiv.org/abs/1903.08536) and its [implementation](https://github.com/Wslsdx/Deep-Learning-Approach-for-Surface-Defect-Detection).

**Comment by Shahdoust** [comment]
@marooncn Thank you for your reply and helpful links. I will try out both ways.
